### ISSUE TITLE
esp8266 nodemcu OTA support

### ISSUE THREAD

**Issue by alcir** [carlosperate/ardublockly#143]
Transferring sketches Over The Air would be interesting.
Or supporting platformio to upload sketches?
What do you think?

Thank you for your efforts.

**Comment by carlosperate** [comment]
At the moment I am not sure it is possible to do OTA from the Arduino IDE command line, so Ardublockly has no access to this functionality. However, if you open the sketch in the IDE (instead of upload, or verify), you should be able to still use that option as normally done with any other Arduino sketch.

Plataform.io would be interesting, but at the moment is outside of the scope of Ardublockly. Working with the Arduino IDE is much simpler and there are ways to get everything ready without using installers or other dependencies.

Thank you for the suggestion though!

**Comment by alcir** [comment]
Thanks
