### ISSUE TITLE
How to run the application from a website.

### ISSUE THREAD

**Issue by DeiverJC** [carlosperate/ardublockly#204]
Hi Carlos.

I thank you for sharing this great project, I was wondering what should I do to be able to run the core of the application from a **web server**?

If the question sounds very obvious or absurd, I beg your pardon.

Thanks for your attention.

**Comment by JulesTopart** [comment]
We actually did it. 
You can simply put all the Js file on server.
We use apache2 to do that. Make sure you made index.html accessible.
You will need to do some little modification in the different javascript concerned.

1. Follow apache2 installation tutorial  : https://doc.ubuntu-fr.org/apache2
2. Directory example : 

```
  var/
    www/
      html/
        .git/
        ardublockly/
        blockly/
        closure-library/
        index.html
```

Note : You will need to change the path of JS script in the index.html
`  <script src="blockly/javascript_compressed.js"></script>`
instead of 
`  <script src="../blockly/javascript_compressed.js"></script>`

Hope it help

**Comment by DeiverJC** [comment]
I'll try.
Thank you very much for your prompt response.
