### ISSUE TITLE
The future of ardublockly and use with others' products?

### ISSUE THREAD

**Issue by MadTooler** [carlosperate/ardublockly#32]
Carlos,

I am not sure how to contact you with a private message through git.

I am nearing completion on a robotic chassis system I have been developing and may also feature on a crowdfunder like kickstarter.  Ardublockly has the potential to be a near perfect fit for what I have in mind for both my basic and more advanced starter kits.

Sure you have this out there under an open license, but do you have any objection to me presenting Ardublockly as a useful tool with my product?

What might be the longer term goals, and achievable timeline, for further development and feature enhancements beyond your todo list?

Thank you.

**Comment by carlosperate** [comment]
Hi,

Of course I have no objections, I'm glad people are finding it useful, and I'm happy to help where possible as well. 

In terms of a general timeline, I need to get the following done as soon as possible due to another project integration as well:
* Static typing to be working without major bugs
* Add back floats
* Rework functions
* Build system to remove closure dependency (reduces load times as well)
* Clean up some of the arduino specific blocks code
* Define a well structured block naming and general patterns so that future updates do not break old saved xml files

Once that is done I need to first work on adding some of the basic Arduino features as blocks (I2C and other out-of-the-box included libraries). I was thinking about also picking a "easy hardware blocks" system, either the seeedstudio grove or the tinker kits, and create some easy to use blocks for that.

From that point onwards I guess there is no specific order for the things I'd like to work on, so if there is any feature that users might find useful I am happy to prioritize that. Otherwise I'll probably start working on changes to be able to run Ardublockly completely headless, and then the "simpler block creator".

About contacting me directly, I am a bit hesitant to write down my email address in public pages (I get enough spam already), so the easiest way to contact me in private would be twitter `@carlosperate` (I've got pms opened for everybody), in case you'd like to continue in private. Either way, my email is really easy to guess from my username and the fact that I am a gmail user :)
