### ISSUE TITLE
Problem with <  and > logic operators during code generation,

### ISSUE THREAD

**Issue by RubensQRZ** [carlosperate/ardublockly#47]
Dear, Carlos.

There is a problem with the code generation when we use the > or < operators,

after the first time you choose one of them in the dropdown list,  you get the simbols  &gt;  and  &lt; into the code instead of the simbols < or >.  I'm workin in that fork I told you and I need solve this problem that also happens in ardublockly.

Best Regards

Rubens.

**Comment by carlosperate** [comment]
I assume you mean `&gt;`  and  `&lt; `, yes the conversion between text and HTML is definitely messing with those symbols, I'll have a look.

(Btw, you can see that the build.py has been updated :)

**Comment by RubensQRZ** [comment]
Thank you so much,  Carlos.

I have not seen the build.py.

I will check

Best Regards

Rubens.

**Comment by carlosperate** [comment]
Sorry it took so long to finally look into this. Should be good to go now :)

**Comment by RubensQRZ** [comment]
Thank you so much, Carlos

Best regards

Rubens

**Comment by RubensQRZ** [comment]
Dear, Carlos.

With the soluction to this problem, another problem arised.

We can not use the symbols  "<" and ">" in the string arguments of addinclude function. To workaround,  i'm now using the html entities in the second argument of this function.

Best regards.

Rubens.

**Comment by carlosperate** [comment]
I see, so that's why the original HTML sanitation was made! I remembered there was a reason, but couldn't find incorrect code generated in my tests for this fix (I should have been looking for missing code, not just scape characters!). 

Please keep in mind that the Arduino code generated and loaded into the IDE (for opening the code, verifying or uploading) bypasses all of this, and therefore should be correct. So if you add the HTML scape characters to the javascript generator function to include them in the C code, then it will be displayed correctly on the application, but shouldn't work on the Arduino IDE (unless you are copying and pasting).

**Comment by RubensQRZ** [comment]
Thank you for de warning, Carlos, I had not yet tried to send the code to the IDE. 

Best regards
